baseURL = "https://informationhot.pages.dev/" # 나중에 실제 도메인으로 바꾸면 됨
title = "informationhot"
theme = "PaperMod"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
[pagination]
  pagerSize = 10


[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "홈"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "블로그"
    url = "/posts/"
    weight = 2
